export const CHARACTER_SEARCH_REQUEST = "CHARACTER_SEARCH_REQUEST";
export const CHARACTER_SEARCH_SUCCESS = "CHARACTER_SEARCH_SUCCESS";
export const CHARACTER_SEARCH_FAIL = "CHARACTER_SEARCH_FAIL";
export const CHARACTER_INFO_REQUEST = "CHARACTER_INFO_REQUEST";
export const CHARACTER_INFO_SUCCESS = "CHARACTER_INFO_SUCCESS";
export const CHARACTER_INFO_FAIL = "CHARACTER_INFO_FAIL";
